apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-provisioner
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              # 指定手动创建的NFS类型的provisioner的名称，提供给StorageClass使用
              value: example.com/nfs
            - name: NFS_SERVER
              # 指定NFS服务器的IP地址
              value: 172.24.253.248
            - name: NFS_PATH
              # 指定NFS服务器的路径
              value: /nfs/data/storageclass
      volumes:
        - name: nfs-client-root
          nfs:
            # 指定NFS服务器的IP地址
            server: 172.24.253.248
            # 指定NFS服务器的路径
            path: /nfs/data/storageclass