#ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
    - host: tomcat.jack.com
      http:
        paths:
          - path: /
            backend:
              serviceName: tomcat-service
              servicePort: 80
