# 以Deployment部署Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  labels:
    app: springboot-demo
spec:
  replicas: 1
  template:
    metadata:
      name: springboot-demo
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image: registry.cn-hangzhou.aliyuncs.com/djflying/springboot-demo:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
      # 设置kubernetes中拉取阿里云镜像仓库镜像的secrets
      imagePullSecrets:
        - name: aliyun-registry
  selector:
    matchLabels:
      app: springboot-demo
---
# 创建Pod的Service
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo
spec:
  selector:
    app: springboot-demo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
---
# 创建Ingress，定义访问规则
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springboot-demo
spec:
  rules:
    - host: springboot.djflying.com
      http:
        paths:
          - path: /
            backend:
              serviceName: springboot-demo
              servicePort: 80