apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo
  labels:
    app: springboot-demo
spec:
  replicas: 1
  template:
    metadata:
      name: springboot-demo
      labels:
        app: springboot-demo
    spec:
      containers:
        - name: springboot-demo
          image:
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: springboot-demo
---
apiVersion: v1
kind: Service
metadata:
  name:
spec:
  selector:
    app:
  ports:
    - port: 8080
  type: NodePort
---
